# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SF
email: fruto.sergio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What I do? I make websites look and behave nice in every browser and device.
  I have 4 years of experience in web development, focusing in HTML, CSS and some help of JS, following the modern standards for Responsive Web Design and Mobile First.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sergiofruto.github.com" # the base hostname & protocol for your site
twitter_username: sergiofruto
github_username:  sergiofruto

# Build settings
markdown: kramdown

include: ['_pages']
